version: 1.0.{build}
build_script:
- ps: >-
    git submodule update --init


    .\node-chakracore\vcbuild.bat chakracore nosign x64


    cd lodash

    npm install

    cp .\patch\qunit-extras.js .\node_modules\qunit-extras\ -force

    cd ..



    md .\ChakraCore\Build\VcBuild\bin\x64_test\buildlogs

    .\ChakraCore\Build\scripts\run_build.ps1 -arch x64 -flavor Test -solutionFile ".\ChakraCore\Build\Chakra.Core.sln" -binDir ".\ChakraCore\Build\VcBuild\bin\x64_test\" -logFile ".\ChakraCore\Build\VcBuild\bin\x64_test\pogo_build_log.txt"


    cp .\node-chakracore\Release\node.exe .\ChakraCore\Build\VcBuild\bin\x64_test\

    cp .\node-chakracore\pgo-config\jscript.config .\ChakraCore\Build\VcBuild\bin\x64_test\ -force


    .\ChakraCore\Build\VcBuild\bin\x64_test\node.exe .\lodash\test\test.js





    md .\ChakraCore\Build\VcBuild\bin\x64_release_pogo\buildlogs

    cp .\node-chakracore\Release\node.exe .\ChakraCore\Build\VcBuild\bin\x64_release_pogo\


    .\ChakraCore\Build\scripts\pogo_build.ps1 -arch x64 -flavor Release -subtype pogo -solutionFile ".\ChakraCore\Build\Chakra.Core.sln" -binpath ".\ChakraCore\Build\VcBuild\bin\x64_release_pogo\" -binDir ".\ChakraCore\Build\VcBuild\bin\x64_release_pogo\" -logFile ".\ChakraCore\Build\VcBuild\bin\x64_release_pogo\pogo_build_log.txt" -scenarios ".\lodash\test\test.js" -binaryName "node.exe"